services:
  alpine-pimptainer:
    image: alpine-pimptainer
    container_name: alpine-pimptainer
    restart: unless-stopped
    ports:
      - "2222:22"
    command: /bin/sh
    stdin_open: true
    tty: true
